"""Shared physical-group tags for PEH plate meshes."""

VOLUME_SUBSTRATE_TAG = 11
VOLUME_PIEZO_TAG = 12

FACET_CLAMPED_TAG = 101
FACET_FREE_X_MAX_TAG = 102
FACET_FREE_Y_MIN_TAG = 103
FACET_FREE_Y_MAX_TAG = 104
FACET_TOP_ELECTRODE_TAG = 105
FACET_BOTTOM_ELECTRODE_TAG = 106
FACET_BOTTOM_PLATE_TAG = 107
